# Inicio del proyecto Estadística Descriptiva

## Instalación de paquetes

In [1]:
# install.packages("MASS")
library(MASS)

In [14]:
data(survey)

## Inspección del dataset

In [16]:
head(survey)

  Sex    Wr.Hnd NW.Hnd W.Hnd Fold    Pulse Clap    Exer Smoke Height M.I
1 Female 18.5   18.0   Right R on L   92   Left    Some Never 173.00 Metric
2 Male   19.5   20.5   Left  R on L  104   Left    None Regul 177.80 Imperial
3 Male   18.0   13.3   Right L on R   87   Neither None Occas     NA NA
4 Male   18.8   18.9   Right R on L   NA   Neither None Never 160.00 Metric
5 Male   20.0   20.0   Right Neither  35   Right   Some Never 165.00 Metric
6 Female 18.0   17.7   Right L on R   64   Right   Some Never 172.72 Imperial
  Age
1 18.250
2 17.583
3 16.917
4 20.333
5 23.667
6 21.000

In [12]:
survey_filtrado <- survey[, c(1, 2, 3, 4, 6, 10)]
head(survey_filtrado)

  Sex    Wr.Hnd NW.Hnd W.Hnd Pulse Height
1 Female 18.5   18.0   Right  92   173.00
2 Male   19.5   20.5   Left  104   177.80
3 Male   18.0   13.3   Right  87       NA
4 Male   18.8   18.9   Right  NA   160.00
5 Male   20.0   20.0   Right  35   165.00
6 Female 18.0   17.7   Right  64   172.72

In [7]:
nrow(survey_filtrado)

[1] 237

In [8]:
ncol(survey_filtrado)

[1] 6

In [10]:
dim(survey_filtrado)

[1] 237   6

In [11]:
survey_limpio <- na.omit(survey_filtrado)
nrow(survey_limpio)

[1] 168

In [17]:
head(survey_limpio)

  Sex    Wr.Hnd NW.Hnd W.Hnd Pulse Height
1 Female 18.5   18.0   Right  92   173.00
2 Male   19.5   20.5   Left  104   177.80
5 Male   20.0   20.0   Right  35   165.00
6 Female 18.0   17.7   Right  64   172.72
7 Male   17.7   17.7   Right  83   182.88
8 Female 17.0   17.3   Right  74   157.00

In [22]:
dim(survey_limpio)

[1] 168   6